name: Publish Docker image
on:
  release:
    types: [published]
jobs:
  docker:
      runs-on: ubuntu-latest
      steps:
        -
          name: Checkout
          uses: actions/checkout@v2
        -
          name: Docker meta
          id: docker_meta
          uses: crazy-max/ghaction-docker-meta@v1
          with:
            images: rueedlinger/vue-connect
            tag-latest: false
            tag-semver: "{{version}}"
        -
          name: Set up QEMU
          uses: docker/setup-qemu-action@v1
        -
          name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1
        -
          name: Login to DockerHub
          uses: docker/login-action@v1 
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
        -
          name: Build and push Docker image
          id: docker_build
          uses: docker/build-push-action@v2
          with:
            context: .
            file: ./Dockerfile
            push: true
            tags: ${{ steps.docker_meta.outputs.tags }}
            labels: ${{ steps.docker_meta.outputs.labels }}
            build-args: |
              IMAGE_VERSION=${{ steps.docker_meta.outputs.version }}
              IMAGE_TAGS=${{ steps.docker_meta.outputs.tags }}
              IMAGE_LABELS=${{ steps.docker_meta.outputs.labels }}
              IMAGE_DIGEST=${{ steps.docker_build.outputs.digest }}